environment:
  matrix:
    - nodejs_version: ""
    - nodejs_version: "8" # LTS Jan 20
    - nodejs_version: "6" # LTS Apr 19
platform:
- x64
cache:
# - "%LOCALAPPDATA%\\Yarn"
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- yarn
test_script:
- yarn test
build: off
