environment:
  matrix:
    - nodejs_version: ""
    - nodejs_version: 12 # EOL Apr 22
    - nodejs_version: 10 # EOL Apr 21
platform:
- x64
install:
- ps: Install-Product node $env:nodejs_version $env:platform
- yarn install --frozen-lockfile
test_script:
- yarn test
build: off
