version: '2'
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 6
plugins:
  duplication:
    enabled: false
  eslint:
    enabled: true
    config:
      config: .eslintrc.yml
  fixme:
    enabled: true
  # Waiting on https://github.com/nodesecurity/nsp/pull/142 to support yarn.lock
  nodesecurity:
    enabled: false
  shellcheck:
    enabled: true
exclude_patterns:
- "packages/**/src/*.spec.js"
- "!packages/**/src"
