os:
- linux
- osx
language: node_js
node_js:
- node
- 7
- 6
- 5
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
script:
- yarn test
after_success:
- bash yarn.sh
- travis_retry yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < test/coverage/lcov.info
addons:
  code_climate:
    repo_token:
