os:
- linux
#- osx
language: node_js
node_js:
- node
- 8 # EOL Dec 19
- 6 # EOL Apr 19
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
  allow_failures:
    - node_js: 6
after_install: yarn bootstrap
script: yarn test
after_success:
- travis_retry yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 7a4b78747587abb295ccb41439d7d067b9de2d885a766e7e88d5e8409599d2ea
