os:
- linux
- osx
language: node_js
node_js:
- node
- 7
- 6
cache:
  yarn: true
sudo: false
matrix:
  fast_finish: true
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
- yarn test
after_script: greenkeeper-lockfile-upload
after_success:
- travis_retry yarn global add codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
addons:
  code_climate:
    repo_token: 7a4b78747587abb295ccb41439d7d067b9de2d885a766e7e88d5e8409599d2ea
notifications:
  email: false
