name: Jest Test Coverage
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ziishaned/jest-reporter-action@@0.1.1
      env:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: 'yarn jest --coverage'
