name: Jest
on: ['pull_request', 'push']
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Tests
      uses: rkusa/jest-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
